### ISSUE TITLE
Bot quits on ratelimit

### ISSUE THREAD

**Issue by cystic** [cystic/iota4earth-bot#1]
('Bot replying to : ', u'want to produce intelligent sustainable furniture #iota4earth')
Traceback (most recent call last):
  File "i4e.py", line 37, in <module>
    submission.reply("Thank you for your contribution to the Earth. +200 IOTA")
  File "/Library/Python/2.7/site-packages/praw/models/reddit/mixins/replyable.py", line 16, in reply
    return self._reddit.post(API_PATH['comment'], data=data)[0]
  File "/Library/Python/2.7/site-packages/praw/reddit.py", line 432, in post
    return self._objector.objectify(data)
  File "/Library/Python/2.7/site-packages/praw/objector.py", line 122, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: RATELIMIT: 'you are doing that too much. try again in 1 minute.' on field 'ratelimit'
Macs-Mac-mini:iota4earth MacMini$ python i4e.py
('Bot replying to : ', u"Introducing Sno-Caps - The People's Cap-And-Trade (2014 MIT Award Winner) #iota4earth")
Traceback (most recent call last):
  File "i4e.py", line 37, in <module>
    submission.reply("Thank you for your contribution to the Earth. +200 IOTA")
  File "/Library/Python/2.7/site-packages/praw/models/reddit/mixins/replyable.py", line 16, in reply
    return self._reddit.post(API_PATH['comment'], data=data)[0]
  File "/Library/Python/2.7/site-packages/praw/reddit.py", line 432, in post
    return self._objector.objectify(data)
  File "/Library/Python/2.7/site-packages/praw/objector.py", line 122, in objectify
    raise APIException(*errors[0])
praw.exceptions.APIException: RATELIMIT: 'you are doing that too much. try again in 9 minutes.' on field 'ratelimit'

**Comment by cystic** [comment]
Should be resolved when the bot gets added as an approved submitter or moderator.
